In [ ]:
import numpy as np #陣列相關套件numerical Python
import pandas as pd #處理一維行別稱Series,處理二維行別稱DataFrame,處理三維行別稱Panel
import matplotlib.pyplot as plt #好用的Python 繪圖套件
array = np.zeros((2,3)) #宣告一個2*3的陣列也就是有兩個一維陣列,每一個一維陣列有三個元素
print(array)
array = np.zeros((2,3),dtype = np.intc)#產生一個內容值皆為0的2*4二維陣列
print(array)
array = np.ones((2,4),dtype = np.intc)#產生一個內容值皆為1的2*4二維陣列
print(array)
array = np.array([[1,2,3],[4,5,6]],dtype=np.intc) #產生一個自訂元素內容2*3二維陣列
print(array)
print("二維陣列的元素大小:",array.size) 
print("二維陣列中第一個陣列中的第二個元素:",array[0][1])
print("二維陣列中第一個陣列所有元素",array[0])
#將二維陣列中第一個陣列中的第二個元素的值改成100
array[0][1]=100
print("二維陣列中第一個陣列所有元素",array[0])
array = np.arange(12) #產生有十二個元素的一維陣列
print(array)
array = np.arange(12,20) #產生一維陣列給定起始值及結束值
print(array)
array = np.arange(12,20,2) #產生一維陣列並給定起始值及結束值,中間間隔為偶數
print(array)
print(array[0]) #陣列第一個值
array[2] = 28 #將陣列中的第三個元素改成28
print(array.size)
#array[5] = 100
#print()

[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]
[[1 1 1 1]
 [1 1 1 1]]
[[1 2 3]
 [4 5 6]]
二維陣列中第一個陣列中的第二個元素: 2
二維陣列中第一個陣列所有元素 [1 2 3]
二維陣列中第一個陣列所有元素 [  1 100   3]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[12 13 14 15 16 17 18 19]
[12 14 16 18]
12


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
txtName1 ="/content/drive/MyDrive/2022Python/迴歸資料01.csv" 
txtName2 ="/content/drive/MyDrive/2022Python/分類資料01.tsv"
df = pd.read_csv(txtName1)
#print(df.info())
#讀取無標頭
df2 = pd.read_csv(txtName2, sep="\t",header=None )
#沒有header=None的話,第一筆資料會被以為是header
#print(df2.info())


#將遊戲時間下的所有元素存在陣列中
X = df["遊戲時間"]
print(X)
#將分數項目下的元素存在陣列中
Y =df.分數
#print(Y)

X=df2[0]
print(X)

header = ["體重","身高","性別"] #0男1女
df2.columns = header
#print(df2)
#以陣列讀取某筆資料
record = df.iloc[1]
print(record,end="\n\n")
#讀取前兩筆資料
records=df.iloc[:2]
print(records,end="\n\n")
#讀取奇數筆資料
records=df.iloc[::2]
print(records)

0     4.3
1     9.2
2     3.5
3     3.0
4    12.5
5     7.5
6     5.5
Name: 遊戲時間, dtype: float64
0    55
1    62
2    78
3    91
4    35
5    42
6    46
7    40
Name: 0, dtype: int64
遊戲時間     9.2
分數      46.0
Name: 1, dtype: float64

   遊戲時間  分數
0   4.3  76
1   9.2  46

   遊戲時間  分數
0   4.3  76
2   3.5  92
4  12.5  50
6   5.5  78


In [ ]:
# dataframe元素的過濾與匯出

print(type(df2["性別"]==0))
print(df2["性別"]==0)

In [ ]:
df3 = df2[df2["性別"]==0]
print(df3)

In [11]:
df3 = df2[df2["身高"]>160]
print(df3)

   體重   身高  性別
0  55  168   0
1  62  172   0
2  78  169   0
3  91  182   0
7  40  161   1


In [12]:
txtName3 = "//content/drive/MyDrive/2022Python/choiced.xls"
df3.to_excel(txtName3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  
